=pod

=head1 NAME

wmcpufreq - dockapp that displays CPU frequency

=head1 SYNOPSIS

B<wmcpufreq> [B<-v>] [B<-exe> I<program>] [B<-cpuid> I<n>[,...]]

=head1 DESCRIPTION

B<wmcpufreq> is a dockapp that displays the CPU frequency.

For one CPU B<wmcpufreq> displays:

=over 2

=item *

The frequency in use between the maximum and minimum.

=item *

The driver in green.

=item *

The active governor in red.

=back

For more CPUs B<wmcpufreq> displays:

=over 2

=item *

The frequency in use between the maximum and minimum.

=item *

The active governor in red.

=back

=head1 OPTIONS

=over

=item B<-v>

Print version and exit.

=item B<-exe> I<program>

The I<program> to be launched when clicking on the B<wmcpufreq> icon.

=item B<-cpuid> I<n>[,...]

Show the frequency in use for CPUI<n>, where I<n> >= 0.
That allows to launch various instances to monitor more than 4 CPUs.

Example: -cpuid 0,2,4

=back

=head1 BUGS

A lot.

=cut
