Index: wmmatrix-0.2/Makefile
===================================================================
--- wmmatrix-0.2.orig/Makefile	2007-08-16 15:58:39.000000000 +0530
+++ wmmatrix-0.2/Makefile	2007-08-16 15:58:44.000000000 +0530
@@ -34,5 +34,5 @@
 	rm -f wmMatrix
 
 install:: wmMatrix
-	install -c -s -m 0755 wmMatrix $(DESTDIR)/bin
+	install -c -m 0755 wmMatrix $(DESTDIR)/bin
 
