.\" wmmatrix manual page
.Dd October 14, 2024
.Dt wmmatrix 1
.Os
.\" ==================================================================
.Sh NAME
.Nm wmmatrix
.Op Fl h
.Op Fl sml
.Op Fl med
.Op Fl lrg
.\" ==================================================================
.Sh DESCRIPTION
.Nm
displays the Matrix digital rain in a dockable window.
The Matrix digital rain, also known as Matrix code, is the iconic
computer code seen in both the Ghost in The Shell and Matrix series.
This cascading green code visually represents the activity within the
simulated reality of the Matrix, brought to life through kinetic
typography.
.Pp
Every Matrix film, along with the spin-off The Animatrix episodes,
begins with this distinctive code.
.\" ==================================================================
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Display list of command-line options.
.It Fl sml
Use small characters for the display.
.It Fl med
Use medium-sized characters for the display.
.It Fl lrg
Use large characters for the display.
.El
.\" ==================================================================
.Sh AUTHORS
.An Michael G. Henderson Aq Mt mghenderson@lanl.gov .
.Pp
Manual page created by
.An Alexandr Savca Aq Mt alexandr.savca89@gmail.com .
.\"
.\" End of file.
